<?php

/**
 * @file
 * Contains saplings_custom functionality.
 */

use Drupal\node\NodeInterface;
use Drupal\ui_skins\HookHandler\PageTop;

/**
 * Implements hook_preprocess_html() for html templates.
 *
 * Adds a meta tag for a field if it has value.
 */
function saplings_custom_preprocess_html(array &$variables) {
  // Load the node entity from current route.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface) {
    // Get the value of the field.
    if ($node->hasField('sa_robots')) {
      $robots_field = $node->get('sa_robots')->getString();
      // Only render if the field has value.
      if ($robots_field) {
        $variables['page']['#attached']['html_head'][] = [
          [
            '#tag' => 'meta',
            '#attributes' => [
              'name' => 'robots',
              'content' => $robots_field,
            ],
          ],
          'robots',
        ];
      }
    }
  }
}

/**
 * Implements hook_page_top().
 */
function saplings_custom_page_top(array &$page_top): void {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $default_theme = \Drupal::config('system.theme')->get('default');
    // /** @var \Drupal\ui_skins\HookHandler\PageTop $instance */
    $instance = \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(PageTop::class);
    $instance->alter($page_top, $default_theme);
  }
}
