<?php

/**
 * @file
 * Contains saplings_custom functionality.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_html() for html templates.
 *
 * Adds a meta tag for a field if it has value.
 */
function saplings_custom_preprocess_html(array &$variables) {
  // Load the node entity from current route.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface) {
    // Get the value of the field.
    if ($node->hasField('sa_robots')) {
      $robots_field = $node->get('sa_robots')->getString();
      // Only render if the field has value.
      if ($robots_field) {
        $variables['page']['#attached']['html_head'][] = [
          [
            '#tag' => 'meta',
            '#attributes' => [
              'name' => 'robots',
              'content' => $robots_field,
            ],
          ],
          'robots',
        ];
      }
    }
  }
}

/**
 * Implements hook_page_attachments().
 */
function saplings_custom_page_attachments(array &$attachments) {
  // Remove environment_indicator_ribbon library and settings from the frontend
  // editing form to avoid overlapping.
  $module_handler = \Drupal::moduleHandler();
  if (!$module_handler->moduleExists('environment_indicator_ribbon')) {
    return;
  }

  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  if ($route_name !== 'frontend_editing.form') {
    return;
  }

  $attached = &$attachments['#attached'];

  // Unattach library and settings as added by the environment_indicator_ribbon
  // module. @see environment_indicator_ribbon_page_attachments().
  unset($attached['drupalSettings']['environment_indicator_ribbon']);
  if (isset($attached['library'])) {
    $attached['library'] = array_diff(
      $attached['library'],
      ['environment_indicator_ribbon/environment_indicator_ribbon']
    );
  }
}
